services:
  multitrack-postgres:
    image: postgres:17
    container_name: multitrack_database
    restart: always
    environment:
      POSTGRES_USER: sys1002
      POSTGRES_PASSWORD: mysecretpassword
      POSTGRES_DB: multitrack_db
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    shm_size: 128mb

volumes:
  pgdata:
    